
spring:
  application:
    name: Sprout
  datasource:
    url: jdbc:h2:file:~/IdeaProjects/h2testdb
    driverClassName: org.h2.Driver
    username: playboy
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update   # can be, create, create-drop, update, validate, none
    show-sql: true

  database: h2
